// export const BASE_URL = process.env.NODE_ENV === 'development' ? 'http://localhost:5000' : '';
export const BASE_URL = '';
export const PRODUCTS_URL = '/api/products';
export const USERS_URL = '/api/users';
export const ORDERS_URL = '/api/orders';
export const RAZORPAY_URL = '/api/config/razorpay';
export const PAYPAL_URL = '/api/config/paypal';
export const RAZORPAY_CALLBACK_URL = '/api/orders';
export const SHIPPING_RATE = 120;
export const FREE_SHIPPING_AMOUNT = 1000;
export const UPLOAD_URL = '/api/upload';